let mix = require("laravel-mix");
let tailwindcsss = require('tailwindcss');

//by default generated by yarn==>
// mix.js('resources/Js/app.js', 'public/Js/app.js').setPublicPath('dist');

when using tailwind cdn =>
mix
  .js("resources/Js/app.js", "public/Js/app.js")
  .sass("resources/scss/app.scss", "public/Css/app.css");

// official on tailwind site =>
// mix
//   .js("resources/js/app.js", "public/js")
//   .postCss("resources/css/app.css", "public/css", [require("tailwindcss")]);

//Modified by Me =>
// mix
//   .js("resources/Js/app.js", "public/Js/app.js")
//   .postCss("resources/scss/app.scss", "public/Css/app.css", [
//     require({tailwindcsss}),
//   ]);
